sonar.organization=richardlnnr
sonar.projectKey=richardlnnr_jumbo-store-locator

sonar.sources=app,nuxt.config.ts
sonar.tests=app
sonar.test.inclusions=**/*.test.ts,**/*.nuxt.test.ts
sonar.exclusions=**/*.test.ts,**/*.nuxt.test.ts,**/*.mock.ts
sonar.coverage.exclusions=\
    **/*.test.ts,\
    **/*.nuxt.test.ts,\
    **/*.mock.ts,\
    **/*.config.*,\
    eslint.config.mjs

sonar.javascript.lcov.reportPaths=coverage/lcov.info
